import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; 
import "./globals.css";

// Configure Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "A Next.js application generated by the Create Next App utility.",
};

export default function RootLayout({
  children,
}: React.PropsWithChildren) {
  return (
    <html lang="en" className={montserrat.className}> 
      <body>
        {children}
      </body>
    </html>
  );
}
